package duan1.qlquannet;

import duan1.Controller.MayTinhController;
import duan1.Controller.QLQuanNetController;
import duan1.dao.MayTinhDAO;
import duan1.dao.PhieuSuDungDAO;
import duan1.dao.impl.MayTinhDAOImpl;
import duan1.dao.impl.PhieuSuDungDAOIpml;
import duan1.entity.MayTinh;
import duan1.entity.PhienSuDung;
import duan1.util.TimeRange;
import duan1.util.XAuth;
import duan1.util.XDate;
import duan1.util.XDialog;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Timestamp;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author pc
 */
public class QLQuanNet extends javax.swing.JFrame implements QLQuanNetController {

    /**
     * Creates new form QLQuanNet
     */
    public QLQuanNet() {
        initComponents();

        tblMay.setModel(new DefaultTableModel(
                new Object[][]{},
                new String[]{"Mã máy", "Thời gian bắt đầu", "Thời gian kết thúc", "Tổng tiền"}
        ));

        DefaultTableModel modelThongKe = new DefaultTableModel(
                new Object[][]{},
                new String[]{"Mã Phiếu", "Mã Máy", "Tên Nhân Viên", "Thời gian bắt đầu", "Thời gian kết thúc", "Tổng tiền"}
        );
        tblThongKe.setModel(modelThongKe);

        this.init();
        this.loadDanhSachMay();
    }

    public void init() {
        this.setLocationRelativeTo(null);
        this.showWelcomeJDialog(this);
        this.showLoginJDialog(this);
        txtGiaTien.setText(String.valueOf(donGiaTheoGio));

        btnThemMay.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnThemMayActionPerformed(evt);
            }
        });
//    if (XAuth.nhanvien.isChucVu()) {
//        // Chức vụ là true → hiện các nút và cho sửa giá tiền
//        btnNhanVien.setVisible(true);
//        btnCapNhat1.setVisible(true);
//        txtGiaTien.setEditable(true);
//    } else {
//        // Chức vụ là false → ẩn các nút và không cho sửa giá tiền
//        btnNhanVien.setVisible(false);
//        btnCapNhat1.setVisible(false);
//        txtGiaTien.setEditable(false);
//    }
    }

    MayTinhDAO maytinhDAO = new MayTinhDAOImpl();

    private Map<Integer, LocalTime> thoiGianBatDauTheoMay = new HashMap<>();

    private double donGiaTheoGio = 10000; // Mặc định 10.000 VNĐ/giờ

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMay = new javax.swing.JTable();
        pnlMayTinh = new javax.swing.JPanel();
        pnlChiTiet = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtMaMay = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTGBatDau = new javax.swing.JTextField();
        btnTinhTien = new javax.swing.JButton();
        txtTGKetThuc = new javax.swing.JTextField();
        txtTongTG = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        movePrevious = new javax.swing.JButton();
        moveFirst = new javax.swing.JButton();
        moveLast = new javax.swing.JButton();
        moveNext = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtGiaTien = new javax.swing.JTextField();
        btnCapNhat1 = new javax.swing.JButton();
        btnThemMay = new javax.swing.JButton();
        btnMoMay = new javax.swing.JButton();
        btnTatMay = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtEnd = new javax.swing.JTextField();
        cboTimeRanges = new javax.swing.JComboBox<>();
        btnLoc = new javax.swing.JButton();
        lblBegin = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblThongKe = new javax.swing.JTable();
        txtBegin = new javax.swing.JTextField();
        lblEnd = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnDangXuat = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnDoiMatKhau = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblMay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã máy", "Thời gian bắt đầu", "Thời gian kết thúc", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblMay);

        pnlMayTinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlMayTinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMayTinhMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlMayTinhLayout = new javax.swing.GroupLayout(pnlMayTinh);
        pnlMayTinh.setLayout(pnlMayTinhLayout);
        pnlMayTinhLayout.setHorizontalGroup(
            pnlMayTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );
        pnlMayTinhLayout.setVerticalGroup(
            pnlMayTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        pnlChiTiet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlChiTietMouseClicked(evt);
            }
        });

        jLabel6.setText("Mã máy:");

        jLabel7.setText("Thời gian bắt đầu:");

        jLabel8.setText("Thời gian kết thúc:");

        txtTGBatDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTGBatDauActionPerformed(evt);
            }
        });

        btnTinhTien.setText("Tính Tiền");
        btnTinhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTienActionPerformed(evt);
            }
        });

        jLabel9.setText("Tổng thời gian chơi:");

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel14.setText("Tổng tiền:");

        txtTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienActionPerformed(evt);
            }
        });

        movePrevious.setText("|<");
        movePrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movePreviousActionPerformed(evt);
            }
        });

        moveFirst.setText("|<<");
        moveFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveFirstActionPerformed(evt);
            }
        });

        moveLast.setText(">>|");
        moveLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveLastActionPerformed(evt);
            }
        });

        moveNext.setText(">|");
        moveNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveNextActionPerformed(evt);
            }
        });

        jLabel2.setText("Giá tiền:");

        txtGiaTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaTienActionPerformed(evt);
            }
        });

        btnCapNhat1.setText("Cập Nhật");
        btnCapNhat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhat1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlChiTietLayout = new javax.swing.GroupLayout(pnlChiTiet);
        pnlChiTiet.setLayout(pnlChiTietLayout);
        pnlChiTietLayout.setHorizontalGroup(
            pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChiTietLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlChiTietLayout.createSequentialGroup()
                        .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14)
                            .addComponent(jLabel2))
                        .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlChiTietLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTongTG, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlChiTietLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlChiTietLayout.createSequentialGroup()
                                        .addComponent(moveFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(movePrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(moveNext, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(moveLast, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlChiTietLayout.createSequentialGroup()
                                        .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnTinhTien, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                            .addComponent(txtGiaTien))
                                        .addGap(71, 71, 71)
                                        .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnCapNhat1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(pnlChiTietLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTGKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlChiTietLayout.createSequentialGroup()
                        .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(43, 43, 43)
                        .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTGBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaMay, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        pnlChiTietLayout.setVerticalGroup(
            pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChiTietLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMaMay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTGBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTGKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTongTG)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTinhTien)
                    .addComponent(btnThoat))
                .addGap(24, 24, 24)
                .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat1))
                .addGap(24, 24, 24)
                .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moveFirst)
                    .addComponent(movePrevious)
                    .addComponent(moveLast)
                    .addComponent(moveNext))
                .addContainerGap())
        );

        btnThemMay.setText("Thêm Máy");
        btnThemMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMayActionPerformed(evt);
            }
        });

        btnMoMay.setText("Mở máy");
        btnMoMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoMayActionPerformed(evt);
            }
        });

        btnTatMay.setText("Tắt máy");
        btnTatMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTatMayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlMayTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnThemMay)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMoMay)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTatMay)))
                        .addGap(18, 18, 18)
                        .addComponent(pnlChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pnlMayTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemMay)
                            .addComponent(btnMoMay)
                            .addComponent(btnTatMay))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        jTabbedPane1.addTab("Máy", jPanel2);

        txtEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndActionPerformed(evt);
            }
        });

        cboTimeRanges.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hôm này", "Tuần này", "Tháng này", "Quý này", "Năm này" }));
        cboTimeRanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTimeRangesActionPerformed(evt);
            }
        });

        btnLoc.setText("Lọc");
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        lblBegin.setText("Từ ngày:");

        tblThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Phiếu", "Mã Máy", "Tên Nhân Viên", "Thời gian bắt đầu", "Thời gian kết thúc", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblThongKeMouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(tblThongKe);

        lblEnd.setText("Đến ngày:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(lblBegin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBegin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEnd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboTimeRanges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEnd)
                    .addComponent(txtBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBegin)
                    .addComponent(cboTimeRanges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thống kê", jPanel1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("QUẢN LÝ QUÁN NET");

        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        btnNhanVien.setText("Nhân viên");
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        btnDoiMatKhau.setText("Đổi mật khẩu");
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDoiMatKhau)
                        .addGap(18, 18, 18)
                        .addComponent(btnNhanVien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDangXuat)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangXuat)
                    .addComponent(btnNhanVien)
                    .addComponent(btnDoiMatKhau))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
        // TODO add your handling code here:
        this.showChangePasswordJDialog(this);
    }//GEN-LAST:event_btnDoiMatKhauActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here:
        this.showUserManagerJDialog(this);
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here
        if (XDialog.confirm("Bạn muốn đăng xuất?")) {
            this.showLoginJDialog(this);
        }
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.open();
    }//GEN-LAST:event_formWindowOpened

    private void tblThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongKeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblThongKeMouseEntered

    private void tblThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongKeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblThongKeMouseClicked

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        this.fillToTable();

    }//GEN-LAST:event_btnLocActionPerformed

    private void cboTimeRangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTimeRangesActionPerformed
        this.selectTimeRange();
    }//GEN-LAST:event_cboTimeRangesActionPerformed

    private void txtEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndActionPerformed

    private void pnlMayTinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMayTinhMouseClicked
        // TODO add your handling code here:
        this.fillToTable();
    }//GEN-LAST:event_pnlMayTinhMouseClicked

    private void btnTinhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTienActionPerformed
        // TODO add your handling code here:
        tinhTongThoiGianChoi();
    }//GEN-LAST:event_btnTinhTienActionPerformed

    private void pnlChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlChiTietMouseClicked
        // TODO add your handling code here:
        //this.fillToTable();
    }//GEN-LAST:event_pnlChiTietMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.clear();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnThemMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMayActionPerformed
        // TODO add your handling code here:
        try {
            // Nhập mã máy
            String maMayStr = JOptionPane.showInputDialog(this, "Nhập mã máy:");
            if (maMayStr == null || maMayStr.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã máy!");
                return;
            }

            int maMay = Integer.parseInt(maMayStr.trim());

            // Kiểm tra mã máy đã tồn tại chưa
            if (maytinh.findByID(maMay) != null) {
                JOptionPane.showMessageDialog(this, "Mã máy đã tồn tại!");
                return;
            }

            // === BỎ CHỌN LOẠI MÁY ===
            // Gán cố định loại máy là 1 (máy thường)
            int maLoai = 1;

            // Tạo đối tượng máy mới
            MayTinh may = new MayTinh();
            may.setMaMay(maMay);
            may.setMaLoai(maLoai); // Vẫn cần nếu trong DB có cột MaLoai

            // Thêm vào DB
            maytinh.insert(may);

            // Tải lại danh sách máy
            loadDanhSachMay();

            JOptionPane.showMessageDialog(this, "Thêm máy thành công!");

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Mã máy phải là số!");
        } catch (Exception ex) {
    if (ex.getMessage().contains("PRIMARY KEY") || ex.getMessage().contains("duplicate key")) {
        JOptionPane.showMessageDialog(this, "Mã máy đã tồn tại trong cơ sở dữ liệu!");
    } else {
        JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
    }
        }
    }//GEN-LAST:event_btnThemMayActionPerformed

    private void moveLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveLastActionPerformed
        // TODO add your handling code here:
        this.moveLast();
    }//GEN-LAST:event_moveLastActionPerformed

    private void moveNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveNextActionPerformed
        this.moveNext();
    }//GEN-LAST:event_moveNextActionPerformed

    private void txtTGBatDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTGBatDauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTGBatDauActionPerformed

    private void movePreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movePreviousActionPerformed
        this.movePrevious();
    }//GEN-LAST:event_movePreviousActionPerformed

    private void moveFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveFirstActionPerformed
        this.moveFirst();
    }//GEN-LAST:event_moveFirstActionPerformed

    private void btnMoMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoMayActionPerformed
        if (mayDangChon == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một máy để mở.");
            return;
        }

        if (mayDangChon.getTrangThai() == 1) {
            JOptionPane.showMessageDialog(this, "Máy đang hoạt động rồi!");
            return;
        }

        // Nếu máy đang tắt → cho mở máy
        mayDangChon.setTrangThai(1); // cập nhật trạng thái trong object

        // cập nhật trạng thái trong DB
        MayTinhDAO mayTinhDAO = new MayTinhDAOImpl();
        mayTinhDAO.updateTrangThai(mayDangChon.getMaMay(), 1);

        if (selectedButton != null) {
            selectedButton.setBackground(Color.GREEN);
        }

        // ===== Ghi nhận thời gian bắt đầu =====
        LocalTime now = LocalTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
        txtTGBatDau.setText(now.format(formatter));

        // ✅ Lưu thời gian vào Map để dùng lại nếu bị clear
        thoiGianBatDauTheoMay.put(mayDangChon.getMaMay(), now);

        // Xóa dữ liệu cũ
        txtTGKetThuc.setText("");
        txtTongTG.setText("");
        txtTongTien.setText("");

        JOptionPane.showMessageDialog(this, "Mở máy thành công!");

    }//GEN-LAST:event_btnMoMayActionPerformed

    private void btnTatMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTatMayActionPerformed
            // TODO add your handling code here:
       
   if (mayDangChon == null || selectedButton == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn máy cần tắt!");
            return;
        }

        if (selectedButton.getBackground().equals(Color.GREEN)) {
            JOptionPane.showMessageDialog(this, "Không thể tắt máy đang hoạt động!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn muốn tắt máy " + mayDangChon.getMaMay() + " không?",
                "Xác nhận tắt",
                JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        MayTinhDAO mayTinhDAO = new MayTinhDAOImpl();
        boolean ketQua = mayTinhDAO.xoaMay(mayDangChon.getMaMay());

        if (ketQua) {
            JOptionPane.showMessageDialog(this, "Tắt máy thành công!");

            // Làm mới danh sách máy
            loadDanhSachMay();

            // Xóa máy khỏi bảng tblMay nếu có
            DefaultTableModel model = (DefaultTableModel) tblMay.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                Object value = model.getValueAt(i, 0);
                if (value != null && Integer.parseInt(value.toString()) == mayDangChon.getMaMay()) {
                    model.removeRow(i);
                    break;
                }
            }

            // Reset thông tin
            txtMaMay.setText("");
            txtTGBatDau.setText("");
            txtTGKetThuc.setText("");
            txtTongTG.setText("");
            txtTongTien.setText("");
            selectedButton = null;
            mayDangChon = null;
        } else {
            JOptionPane.showMessageDialog(this, "Tắt máy thất bại hoặc máy không tồn tại!");
        }


    }//GEN-LAST:event_btnTatMayActionPerformed

    private void txtTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienActionPerformed

    private void btnCapNhat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhat1ActionPerformed
        try {
            double giaMoi = Double.parseDouble(txtGiaTien.getText().trim());

            if (giaMoi <= 0) {
                JOptionPane.showMessageDialog(this, "⚠️ Giá tiền phải lớn hơn 0!");
                return;
            }

            donGiaTheoGio = giaMoi; // ✅ Cập nhật giá tiền thực tế sử dụng
            JOptionPane.showMessageDialog(this, "✅ Đã cập nhật giá tiền: " + giaMoi + " VNĐ/giờ");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, " Giá tiền không hợp lệ!");
        }


    }//GEN-LAST:event_btnCapNhat1ActionPerformed

    private void txtGiaTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaTienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLQuanNet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLQuanNet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLQuanNet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLQuanNet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLQuanNet().setVisible(true);
            }
        });
    }

// Biến toàn cục bạn cần có
    private List<JButton> danhSachButtonMay = new ArrayList<>();
    private int currentButtonIndex = -1; // -1 nếu chưa chọn

    private void moveToButton(int index) {
        if (danhSachButtonMay.isEmpty()) {
            return;
        }

        if (index < 0) {
            index = danhSachButtonMay.size() - 1; // quay lại cuối
        } else if (index >= danhSachButtonMay.size()) {
            index = 0; // quay lại đầu
        }

        currentButtonIndex = index;
        danhSachButtonMay.get(currentButtonIndex).doClick(); // giả lập click nút
    }

    private void moveNextButton() {
        moveToButton(currentButtonIndex + 1);
    }

    private void movePreviousButton() {
        moveToButton(currentButtonIndex - 1);
    }

    private void moveFirstButton() {
        moveToButton(0);
    }

    private void moveLastButton() {
        moveToButton(danhSachButtonMay.size() - 1);
    }

    private MayTinh mayDangChon = null; // Biến lưu máy được chọn hiện tại
    private JButton selectedButton = null; // Nút tương ứng với máy đó

    public void loadDanhSachMay() {
        pnlMayTinh.removeAll(); // Xóa các nút cũ
        danhSachButtonMay.clear(); // Xóa danh sách nút cũ

        MayTinhDAO mayTinhDAO = new MayTinhDAOImpl();
        List<MayTinh> danhSachMay = mayTinhDAO.findAll();

        pnlMayTinh.setLayout(new GridLayout(4, 4, 10, 10));

        for (MayTinh may : danhSachMay) {
            JButton btn = new JButton("Máy " + may.getMaMay());

            // Đổi màu theo trạng thái
            if (may.getTrangThai() == 1) {
                btn.setBackground(Color.GREEN);
            } else {
                btn.setBackground(Color.RED);
            }

            btn.addActionListener(e -> {
                xuLyKhiChonMay(may);
                selectedButton = btn;
                mayDangChon = may;
                currentButtonIndex = danhSachButtonMay.indexOf(btn);
            });

            pnlMayTinh.add(btn);
            danhSachButtonMay.add(btn);
        }

        pnlMayTinh.revalidate();
        pnlMayTinh.repaint();

        // Nếu danh sách máy không rỗng, chọn máy đầu tiên mặc định
        if (!danhSachButtonMay.isEmpty()) {
            currentButtonIndex = 0;
            danhSachButtonMay.get(currentButtonIndex).doClick();
        }
    }

    private void xuLyKhiChonMay(MayTinh may) {
        int maMayChon = may.getMaMay();

        txtMaMay.setText(String.valueOf(maMayChon));

        // ✅ Hiển thị lại thời gian bắt đầu nếu có lưu
        if (thoiGianBatDauTheoMay.containsKey(maMayChon)) {
            LocalTime gioBatDau = thoiGianBatDauTheoMay.get(maMayChon);
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
            txtTGBatDau.setText(gioBatDau.format(formatter));
        } else {
            txtTGBatDau.setText("");
        }

        txtTGKetThuc.setText("");
        txtTongTG.setText("");
        txtTongTien.setText("");

        // Gán máy và button được chọn
        mayDangChon = may;
    }

    private void tinhTongThoiGianChoi() {
        try {
            String batDauStr = txtTGBatDau.getText().trim();

            if (batDauStr.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Chưa có thời gian bắt đầu!");
                return;
            }

            // Parse thời gian bắt đầu
            LocalTime batDau;
            if (batDauStr.length() == 5) {
                batDau = LocalTime.parse(batDauStr, DateTimeFormatter.ofPattern("HH:mm"));
            } else {
                batDau = LocalTime.parse(batDauStr, DateTimeFormatter.ofPattern("HH:mm:ss"));
            }

            // Parse thời gian kết thúc
            String tgketthuc = txtTGKetThuc.getText().trim();
            if (tgketthuc.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Chưa có thời gian kết thúc!");
                return;
            }
            LocalTime ketThuc = LocalTime.parse(tgketthuc, DateTimeFormatter.ofPattern("HH:mm:ss"));

            // Tính thời gian
            Duration duration = Duration.between(batDau, ketThuc);
            if (duration.isNegative()) {
                JOptionPane.showMessageDialog(null, "Thời gian kết thúc phải sau thời gian bắt đầu!");
                return;
            }

            long tongPhut = duration.toMinutes();
            long gio = tongPhut / 60;
            long phut = tongPhut % 60;

            txtTongTG.setText(gio + " giờ " + phut + " phút");

            // ====== TÍNH TIỀN ======
            double giaTienDangDung;
            try {
                giaTienDangDung = Double.parseDouble(txtGiaTien.getText().trim());
                if (giaTienDangDung <= 0) {
                    JOptionPane.showMessageDialog(this, "⚠️ Giá tiền phải lớn hơn 0!");
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "⚠️ Giá tiền không hợp lệ!");
                return;
            }

            double soGioThucTe = tongPhut / 60.0;
            double tongTien = giaTienDangDung * soGioThucTe;
            long tongTienLamTron = ((long) ((tongTien + 999) / 1000)) * 1000;

            txtTongTien.setText(tongTienLamTron + " VNĐ");

            //lưu bản thống kê vào SQL 
            try {
                LocalTime startTime = LocalTime.parse(txtTGBatDau.getText(), DateTimeFormatter.ofPattern("HH:mm:ss"));
                LocalTime endTime = LocalTime.parse(txtTGKetThuc.getText(), DateTimeFormatter.ofPattern("HH:mm:ss"));

                LocalDate today = LocalDate.now();
                Timestamp tgBatDau = Timestamp.valueOf(LocalDateTime.of(today, startTime));
                Timestamp tgKetThuc = Timestamp.valueOf(LocalDateTime.of(today, endTime));

                PhienSuDung phien = new PhienSuDung();
                phien.setTGBatDau(tgBatDau);
                phien.setTGKetThuc(tgKetThuc);
                phien.setMaMay(Integer.parseInt(txtMaMay.getText().trim()));
                phien.setTongTien((int) tongTienLamTron);
                phien.setTenDangNhap("admin"); // Hoặc lấy tên nhân viên đăng nhập thực tế

                PhieuSuDungDAO dao = new PhieuSuDungDAOIpml(); // Chú ý: Tên interface bạn là "PhieuSuDungDAO"
                boolean success = dao.insert(phien);

                if (!success) {
                    JOptionPane.showMessageDialog(this, "❌ Lưu phiên sử dụng thất bại!");
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "❌ Lỗi khi lưu phiên sử dụng vào DB!");
            }

            // ====== CẬP NHẬT / THÊM VÀO tblMay ======
            DefaultTableModel model = (DefaultTableModel) tblMay.getModel();
            int maMay = Integer.parseInt(txtMaMay.getText().trim());

            boolean daCapNhat = false;
            for (int i = 0; i < model.getRowCount(); i++) {
                Object value = model.getValueAt(i, 0);
                if (value != null && Integer.parseInt(value.toString()) == maMay) {
                    // Cập nhật lại hàng cũ
                    model.setValueAt(txtTGBatDau.getText(), i, 1);
                    model.setValueAt(txtTGKetThuc.getText(), i, 2);
                    model.setValueAt(txtTongTien.getText(), i, 3);
                    daCapNhat = true;
                    break;
                }
            }

            if (!daCapNhat) {
                // Thêm mới
                model.addRow(new Object[]{
                    maMay,
                    txtTGBatDau.getText(),
                    txtTGKetThuc.getText(),
                    txtTongTien.getText()
                });
            }

            // Thông báo
            JOptionPane.showMessageDialog(null,
                    "Tổng thời gian: " + gio + " giờ " + phut + " phút\n"
                    + "Tổng tiền: " + String.format("%.0f VNĐ", tongTien));

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi xử lý thời gian hoặc tính tiền!");
        }

        // ====== THÊM DỮ LIỆU VÀO BẢNG THỐNG KÊ ======
        DefaultTableModel modelThongKe = (DefaultTableModel) tblThongKe.getModel();
        String maPhieu = "MP" + System.currentTimeMillis(); // Mã phiếu tạm thời
        String tenNhanVien = "Admin"; // Dùng mặc định nếu không có textbox nhập tên

        int maMay = Integer.parseInt(txtMaMay.getText().trim());

        modelThongKe.addRow(new Object[]{
            maPhieu,
            maMay,
            tenNhanVien,
            txtTGBatDau.getText(),
            txtTGKetThuc.getText(),
            txtTongTien.getText()
        });
        int maMayDaTinh = Integer.parseInt(txtMaMay.getText().trim());

        for (JButton btnMay : danhSachButtonMay) {
            if (btnMay.getText().equals("Máy " + maMayDaTinh)) {
                btnMay.setBackground(Color.RED);
                break; // Đã tìm thấy nút đúng rồi, không cần lặp tiếp
            }
        }
        // Cập nhật trạng thái máy đã sử dụng xong (tắt máy)
        mayDangChon.setTrangThai(0);  // Cập nhật trạng thái trong đối tượng

// Cập nhật trạng thái trong database (nếu có)
        MayTinhDAO mayTinhDAO = new MayTinhDAOImpl();
        mayTinhDAO.updateTrangThai(mayDangChon.getMaMay(), 0);  // Giống hàm đã đề cập trước đó

        thoiGianBatDauTheoMay.remove(maMay);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat1;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton btnMoMay;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnTatMay;
    private javax.swing.JButton btnThemMay;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTinhTien;
    private javax.swing.JComboBox<String> cboTimeRanges;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBegin;
    private javax.swing.JLabel lblEnd;
    private javax.swing.JButton moveFirst;
    private javax.swing.JButton moveLast;
    private javax.swing.JButton moveNext;
    private javax.swing.JButton movePrevious;
    private javax.swing.JPanel pnlChiTiet;
    private javax.swing.JPanel pnlMayTinh;
    private javax.swing.JTable tblMay;
    private javax.swing.JTable tblThongKe;
    private javax.swing.JTextField txtBegin;
    private javax.swing.JTextField txtEnd;
    private javax.swing.JTextField txtGiaTien;
    private javax.swing.JTextField txtMaMay;
    private javax.swing.JTextField txtTGBatDau;
    private javax.swing.JTextField txtTGKetThuc;
    private javax.swing.JTextField txtTongTG;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables

    MayTinhDAO maytinh = new MayTinhDAOImpl() {};
    List<MayTinh> MayTinh = List.of();

    PhieuSuDungDAO phieuSuDungdao = new PhieuSuDungDAOIpml();
    List<PhienSuDung> phieuSuDung = List.of();

    @Override
    public void selectTimeRange() {
        TimeRange range = TimeRange.today();
        switch (cboTimeRanges.getSelectedIndex()) {
            case 0 ->
                range = TimeRange.today();
            case 1 ->
                range = TimeRange.thisWeek();
            case 2 ->
                range = TimeRange.thisMonth();
            case 3 ->
                range = TimeRange.thisQuarter();
            case 4 ->
                range = TimeRange.thisYear();
        }
        txtBegin.setText(XDate.format(range.getBegin(), "MM/dd/yyyy"));
        txtEnd.setText(XDate.format(range.getEnd(), "MM/dd/yyyy"));
        this.fillToTable();
    }

    @Override
    public void open() {
        this.setLocationRelativeTo(null);
        this.fillToTable();
        this.clear();
    }

    @Override
    public void setForm(PhienSuDung entity) {

    }

    @Override
    public PhienSuDung getForm() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void fillToTable() {
        DefaultTableModel modelPSD = (DefaultTableModel) tblThongKe.getModel();
        modelPSD.setRowCount(0);
        Date begin = XDate.parse(txtBegin.getText(), "MM/dd/yyyy");
        Date end = XDate.parse(txtEnd.getText(), "MM/dd/yyyy");
        phieuSuDung = phieuSuDungdao.findByTimeRange(begin, end);
        phieuSuDung.forEach(item -> {
            Object[] rowData = {
                item.getMaPhien(),
                item.getMaMay(),
                item.getTenDangNhap(),
                item.getTGBatDau(),
                item.getTGKetThuc(),
                item.getTongTien(),
                false
            };
            modelPSD.addRow(rowData);
        });
    }

    @Override
    public void edit() {

    }

    @Override
    public void create() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void update() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void delete() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void clear() {
        this.txtMaMay.setText("");
        this.txtTGBatDau.setText("");
        this.txtTGKetThuc.setText("");
        this.tblThongKe.clearSelection();
        this.txtTongTG.setText("");
        this.txtTongTien.setText("");
    }

    @Override
    public void setEditable(boolean editable) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void checkAll() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void uncheckAll() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void deleteCheckedItems() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveFirst() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        moveFirstButton();
    }

    @Override
    public void movePrevious() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        movePreviousButton();
    }

    @Override
    public void moveNext() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        moveNextButton();
    }

    @Override
    public void moveLast() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        moveLastButton();
    }

    @Override
    public void moveTo(int rowIndex) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        moveToButton(rowIndex);
    }
}
